#!/bin/sh

# SSL instructions.
# 1) Do not compile with rtsigio.
# 2) Edit the appropriate points of this script.
# 3) Run this script with bourne shell or bash.
# 4) Restart your ircd after editing the appropriate parts of your ircd.conf.
#
# SSL configuration is recommended for advanced users only, and has many flaws in it's
# implementation.

# DPATH is where you have installed the ircd to.
DPATH="/usr/local/ircd/etc"

CERT_DAYS=365
AUTO_CONFIG="0"
REBUILD_CRT="1"

c=""

	echo " ";
	echo "*** Building a new SSL certificate for your server.";
		FOO=""
		runonce=""
		while [ -z "$FOO" ] ; do
		    FOO="$CERT_DAYS"
		    echo " "
		    echo "How many days will your certificate last ?"
		    echo " "
		    echo -n "[$FOO] -> $c"
		    if [ -z "$AUTO_CONFIG" -o -n "$runonce" -o -z "$SERVICES_NAME" ] ; then
			read cc
			runonce=Yes
		    else
			cc=""
		    fi
		    if [ -z "$cc" ] ; then
			cc=$FOO
		    fi
		    case "$cc" in
		        *)
		            CERT_DAYS="$cc"
		    esac
		done

		openssl req -new -x509 -days $CERT_DAYS -nodes \
			-config ircdssl.cnf -out "$DPATH/cert.pem" \
			-keyout "$DPATH/rsa.key" $RNDF
		openssl x509 -subject -dates -fingerprint -noout \
			-in "$DPATH/cert.pem"


	echo " "
	echo "*** SSL configuration complete."
	echo " "
